### ISSUE TITLE
Correcciones memoria

### ISSUE THREAD

**Issue by alvarag** [jlgarridol/TFM-FIS-IF#5]
[memoriaAAG.pdf](https://github.com/jlgarridol/TFM-FIS-IF/files/4502719/memoriaAAG.pdf)

**Comment by jlgarridol** [comment]
Gracias, lo reviso

**Comment by alvarag** [comment]
Buen trabajo, me ha gustado aunque queda mucho que hacer aún.

[memoriaAAG.pdf](https://github.com/jlgarridol/TFM-FIS-IF/files/4621542/memoriaAAG.pdf)

**Comment by alvarag** [comment]
Adjunto las fotos del montaje en un salón.

![IMG_20200528_140612](https://user-images.githubusercontent.com/9881614/83260120-82944c00-a1b9-11ea-94be-f6d58e6a047a.jpg)

![IMG_20200528_140625](https://user-images.githubusercontent.com/9881614/83260062-6abcc800-a1b9-11ea-919c-d0e217dd39d3.jpg)

**Comment by alvarag** [comment]
Me ha gustado la memoria, todavía hay que pulir cosas pero está muy bien.

[memoria_AAG.pdf](https://github.com/jlgarridol/TFM-FIS-IF/files/4796932/memoria_AAG.pdf)
